"""Edited appartment building table

Revision ID: 713066127743
Revises: 6ad80ed9322a
Create Date: 2022-12-04 12:08:25.802349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '713066127743'
down_revision = '6ad80ed9322a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
